### ISSUE TITLE
SystemUI Crash

### ISSUE THREAD

**Issue by GuaiYiHu** [GuaiYiHu/android_device_xiaomi_violet#2]
--------- beginning of crash
08-24 09:28:48.529  1489  1510 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x10 in tid 1510 (Binder:1489_1), pid 1489 (system_server)
08-24 09:28:48.762  5805  5805 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
08-24 09:28:48.762  5805  5805 F DEBUG   : MoKee Version: 'MK90.0-violet-201908232239-EXPERIMENTAL'
08-24 09:28:48.762  5805  5805 F DEBUG   : Build fingerprint: 'xiaomi/violet/violet:9/PKQ1.181203.001/V10.3.9.0.PFHCNXM:user/release-keys'
08-24 09:28:48.762  5805  5805 F DEBUG   : Revision: '0'
08-24 09:28:48.762  5805  5805 F DEBUG   : ABI: 'arm64'
08-24 09:28:48.762  5805  5805 F DEBUG   : pid: 1489, tid: 1510, name: Binder:1489_1  >>> system_server <<<
08-24 09:28:48.762  5805  5805 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x10
08-24 09:28:48.762  5805  5805 F DEBUG   : Cause: null pointer dereference
08-24 09:28:48.762  5805  5805 F DEBUG   :     x0  000000708d0458a0  x1  0000000000000010  x2  0000000070f10860  x3  0000000000000001
08-24 09:28:48.762  5805  5805 F DEBUG   :     x4  000000708a7158b0  x5  0000000000000000  x6  0000000100000000  x7  0073006700000000
08-24 09:28:48.762  5805  5805 F DEBUG   :     x8  0000000000000000  x9  0000000000000028  x10 0000000000000036  x11 00000070b05f5688
08-24 09:28:48.762  5805  5805 F DEBUG   :     x12 00000070a87e2e88  x13 00000070a87e2f08  x14 0000000000000004  x15 0000000000000000
08-24 09:28:48.762  5805  5805 F DEBUG   :     x16 0000007132af20f8  x17 0000007133d9ce24  x18 0000000000000008  x19 000000708d0458a0
08-24 09:28:48.762  5805  5805 F DEBUG   :     x20 000000708d0458a0  x21 00000070aa01b700  x22 000000708d046588  x23 0000000013b81470
08-24 09:28:48.762  5805  5805 F DEBUG   :     x24 0000000013e51a30  x25 0000000000000001  x26 0000000014124ef0  x27 0000000000000105
08-24 09:28:48.762  5805  5805 F DEBUG   :     x28 0000000000000112  x29 000000708d045890
08-24 09:28:48.762  5805  5805 F DEBUG   :     sp  000000708d045870  lr  000000713299ee50  pc  0000007133d9ce40
08-24 09:28:48.940  5805  5805 F DEBUG   : 
08-24 09:28:48.940  5805  5805 F DEBUG   : backtrace:
08-24 09:28:48.940  5805  5805 F DEBUG   :     #00 pc 00000000000a7e40  /system/lib64/libc++.so (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>::basic_string(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::allocator<char> const&)+28)
08-24 09:28:48.940  5805  5805 F DEBUG   :     #01 pc 00000000000f5e4c  /system/lib64/libandroid_runtime.so (android::android_view_InputChannel_nativeWriteToParcel(_JNIEnv*, _jobject*, _jobject*)+136)
08-24 09:28:48.940  5805  5805 F DEBUG   :     #02 pc 00000000003ad458  /system/framework/arm64/boot-framework.oat (offset 0x39f000) (android.graphics.SurfaceTexture.nativeGetTransformMatrix [DEDUPED]+152)
08-24 09:28:48.940  5805  5805 F DEBUG   :     #03 pc 0000000000c383f8  /system/framework/arm64/boot-framework.oat (offset 0x39f000) (android.view.InputChannel.writeToParcel+56)
08-24 09:28:48.941  5805  5805 F DEBUG   :     #04 pc 00000000006e2328  /system/framework/arm64/boot-framework.oat (offset 0x39f000) (com.android.internal.view.InputBindResult.writeToParcel+184)
08-24 09:28:48.941  5805  5805 F DEBUG   :     #05 pc 0000000000e45fb0  /system/framework/arm64/boot-framework.oat (offset 0x39f000) (com.android.internal.view.IInputMethodManager$Stub.onTransact+5376)
08-24 09:28:48.941  5805  5805 F DEBUG   :     #06 pc 0000000000e9e04c  /system/framework/oat/arm64/services.odex (offset 0x5b4000) (com.android.server.InputMethodManagerService.onTransact+76)
08-24 09:28:48.941  5805  5805 F DEBUG   :     #07 pc 0000000000bd254c  /system/framework/arm64/boot-framework.oat (offset 0x39f000) (android.os.Binder.execTransact+588)
08-24 09:28:48.941  5805  5805 F DEBUG   :     #08 pc 0000000000554988  /system/lib64/libart.so (art_quick_invoke_stub+584)
08-24 09:28:48.941  5805  5805 F DEBUG   :     #09 pc 00000000000cf6c8  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200)
08-24 09:28:48.941  5805  5805 F DEBUG   :     #10 pc 000000000045c884  /system/lib64/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+104)
08-24 09:28:48.941  5805  5805 F DEBUG   :     #11 pc 000000000045dc18  /system/lib64/libart.so (art::InvokeVirtualOrInterfaceWithVarArgs(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+440)
08-24 09:28:48.941  5805  5805 F DEBUG   :     #12 pc 0000000000333e30  /system/lib64/libart.so (art::JNI::CallBooleanMethodV(_JNIEnv*, _jobject*, _jmethodID*, std::__va_list)+656)
08-24 09:28:48.941  5805  5805 F DEBUG   :     #13 pc 00000000000c4794  /system/lib64/libandroid_runtime.so (_JNIEnv::CallBooleanMethod(_jobject*, _jmethodID*, ...)+120)
08-24 09:28:48.941  5805  5805 F DEBUG   :     #14 pc 000000000012e510  /system/lib64/libandroid_runtime.so (JavaBBinder::onTransact(unsigned int, android::Parcel const&, android::Parcel*, unsigned int)+156)
08-24 09:28:48.941  5805  5805 F DEBUG   :     #15 pc 000000000004f998  /system/lib64/libbinder.so (android::BBinder::transact(unsigned int, android::Parcel const&, android::Parcel*, unsigned int)+136)
08-24 09:28:48.941  5805  5805 F DEBUG   :     #16 pc 000000000005aa38  /system/lib64/libbinder.so (android::IPCThreadState::executeCommand(int)+520)
08-24 09:28:48.941  5805  5805 F DEBUG   :     #17 pc 000000000005a774  /system/lib64/libbinder.so (android::IPCThreadState::getAndExecuteCommand()+156)
08-24 09:28:48.941  5805  5805 F DEBUG   :     #18 pc 000000000005ae3c  /system/lib64/libbinder.so (android::IPCThreadState::joinThreadPool(bool)+60)
08-24 09:28:48.941  5805  5805 F DEBUG   :     #19 pc 000000000007b47c  /system/lib64/libbinder.so (android::PoolThread::threadLoop()+24)
08-24 09:28:48.941  5805  5805 F DEBUG   :     #20 pc 000000000000f9d4  /system/lib64/libutils.so (android::Thread::_threadLoop(void*)+280)
08-24 09:28:48.941  5805  5805 F DEBUG   :     #21 pc 00000000000b4d50  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::javaThreadShell(void*)+140)
08-24 09:28:48.941  5805  5805 F DEBUG   :     #22 pc 00000000000833b8  /system/lib64/libc.so (__pthread_start(void*)+36)
08-24 09:28:48.941  5805  5805 F DEBUG   :     #23 pc 00000000000237cc  /system/lib64/libc.so (__start_thread+68)
08-24 09:28:49.926  2666  2666 E AndroidRuntime: FATAL EXCEPTION: main
08-24 09:28:49.926  2666  2666 E AndroidRuntime: Process: com.google.android.gms.persistent, PID: 2666
08-24 09:28:49.926  2666  2666 E AndroidRuntime: DeadSystemException: The system died; earlier logs will point to the root cause
08-24 10:09:48.176  5987  6235 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x10 in tid 6235 (Binder:5987_5), pid 5987 (system_server)
08-24 10:09:48.383 23440 23440 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
08-24 10:09:48.383 23440 23440 F DEBUG   : MoKee Version: 'MK90.0-violet-201908232239-EXPERIMENTAL'
08-24 10:09:48.384 23440 23440 F DEBUG   : Build fingerprint: 'xiaomi/violet/violet:9/PKQ1.181203.001/V10.3.9.0.PFHCNXM:user/release-keys'
08-24 10:09:48.384 23440 23440 F DEBUG   : Revision: '0'
08-24 10:09:48.384 23440 23440 F DEBUG   : ABI: 'arm64'
08-24 10:09:48.384 23440 23440 F DEBUG   : pid: 5987, tid: 6235, name: Binder:5987_5  >>> system_server <<<
08-24 10:09:48.384 23440 23440 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x10
08-24 10:09:48.384 23440 23440 F DEBUG   : Cause: null pointer dereference
08-24 10:09:48.384 23440 23440 F DEBUG   :     x0  000000761dcf88a0  x1  0000000000000010  x2  0000000070f10860  x3  0000000000000001
08-24 10:09:48.384 23440 23440 F DEBUG   :     x4  000000761d8ee860  x5  0000000000000000  x6  0000000100000000  x7  0000005000000000
08-24 10:09:48.384 23440 23440 F DEBUG   :     x8  0000000000000000  x9  0000000000000028  x10 0000000000000036  x11 00000076527e7688
08-24 10:09:48.384 23440 23440 F DEBUG   :     x12 000000761f180288  x13 000000761f180308  x14 0000000000000008  x15 0000000000000000
08-24 10:09:48.384 23440 23440 F DEBUG   :     x16 00000076d78600f8  x17 00000076d505ce24  x18 0000000000000008  x19 000000761dcf88a0
08-24 10:09:48.384 23440 23440 F DEBUG   :     x20 000000761dcf88a0  x21 000000764c1caa00  x22 000000761dcf9588  x23 0000000013300050
08-24 10:09:48.384 23440 23440 F DEBUG   :     x24 00000000132a5258  x25 0000000000000001  x26 0000000013af37a0  x27 0000000000000104
08-24 10:09:48.384 23440 23440 F DEBUG   :     x28 0000000000000110  x29 000000761dcf8890
08-24 10:09:48.384 23440 23440 F DEBUG   :     sp  000000761dcf8870  lr  00000076d770ce50  pc  00000076d505ce40
08-24 10:09:48.561 23440 23440 F DEBUG   : 
08-24 10:09:48.561 23440 23440 F DEBUG   : backtrace:
08-24 10:09:48.561 23440 23440 F DEBUG   :     #00 pc 00000000000a7e40  /system/lib64/libc++.so (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>::basic_string(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::allocator<char> const&)+28)
08-24 10:09:48.561 23440 23440 F DEBUG   :     #01 pc 00000000000f5e4c  /system/lib64/libandroid_runtime.so (android::android_view_InputChannel_nativeWriteToParcel(_JNIEnv*, _jobject*, _jobject*)+136)
08-24 10:09:48.561 23440 23440 F DEBUG   :     #02 pc 00000000003ad458  /system/framework/arm64/boot-framework.oat (offset 0x39f000) (android.graphics.SurfaceTexture.nativeGetTransformMatrix [DEDUPED]+152)
08-24 10:09:48.561 23440 23440 F DEBUG   :     #03 pc 0000000000c383f8  /system/framework/arm64/boot-framework.oat (offset 0x39f000) (android.view.InputChannel.writeToParcel+56)
08-24 10:09:48.561 23440 23440 F DEBUG   :     #04 pc 00000000006e2328  /system/framework/arm64/boot-framework.oat (offset 0x39f000) (com.android.internal.view.InputBindResult.writeToParcel+184)
08-24 10:09:48.561 23440 23440 F DEBUG   :     #05 pc 0000000000e45fb0  /system/framework/arm64/boot-framework.oat (offset 0x39f000) (com.android.internal.view.IInputMethodManager$Stub.onTransact+5376)
08-24 10:09:48.561 23440 23440 F DEBUG   :     #06 pc 0000000000e9e04c  /system/framework/oat/arm64/services.odex (offset 0x5b4000) (com.android.server.InputMethodManagerService.onTransact+76)
08-24 10:09:48.561 23440 23440 F DEBUG   :     #07 pc 0000000000bd254c  /system/framework/arm64/boot-framework.oat (offset 0x39f000) (android.os.Binder.execTransact+588)
08-24 10:09:48.561 23440 23440 F DEBUG   :     #08 pc 0000000000554988  /system/lib64/libart.so (art_quick_invoke_stub+584)
08-24 10:09:48.561 23440 23440 F DEBUG   :     #09 pc 00000000000cf6c8  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200)
08-24 10:09:48.561 23440 23440 F DEBUG   :     #10 pc 000000000045c884  /system/lib64/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+104)
08-24 10:09:48.561 23440 23440 F DEBUG   :     #11 pc 000000000045dc18  /system/lib64/libart.so (art::InvokeVirtualOrInterfaceWithVarArgs(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+440)
08-24 10:09:48.561 23440 23440 F DEBUG   :     #12 pc 0000000000333e30  /system/lib64/libart.so (art::JNI::CallBooleanMethodV(_JNIEnv*, _jobject*, _jmethodID*, std::__va_list)+656)
08-24 10:09:48.561 23440 23440 F DEBUG   :     #13 pc 00000000000c4794  /system/lib64/libandroid_runtime.so (_JNIEnv::CallBooleanMethod(_jobject*, _jmethodID*, ...)+120)
08-24 10:09:48.561 23440 23440 F DEBUG   :     #14 pc 000000000012e510  /system/lib64/libandroid_runtime.so (JavaBBinder::onTransact(unsigned int, android::Parcel const&, android::Parcel*, unsigned int)+156)
08-24 10:09:48.561 23440 23440 F DEBUG   :     #15 pc 000000000004f998  /system/lib64/libbinder.so (android::BBinder::transact(unsigned int, android::Parcel const&, android::Parcel*, unsigned int)+136)
08-24 10:09:48.561 23440 23440 F DEBUG   :     #16 pc 000000000005aa38  /system/lib64/libbinder.so (android::IPCThreadState::executeCommand(int)+520)
08-24 10:09:48.561 23440 23440 F DEBUG   :     #17 pc 000000000005a774  /system/lib64/libbinder.so (android::IPCThreadState::getAndExecuteCommand()+156)
08-24 10:09:48.561 23440 23440 F DEBUG   :     #18 pc 000000000005ae3c  /system/lib64/libbinder.so (android::IPCThreadState::joinThreadPool(bool)+60)
08-24 10:09:48.561 23440 23440 F DEBUG   :     #19 pc 000000000007b47c  /system/lib64/libbinder.so (android::PoolThread::threadLoop()+24)
08-24 10:09:48.561 23440 23440 F DEBUG   :     #20 pc 000000000000f9d4  /system/lib64/libutils.so (android::Thread::_threadLoop(void*)+280)
08-24 10:09:48.561 23440 23440 F DEBUG   :     #21 pc 00000000000b4d50  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::javaThreadShell(void*)+140)
08-24 10:09:48.561 23440 23440 F DEBUG   :     #22 pc 00000000000833b8  /system/lib64/libc.so (__pthread_start(void*)+36)
08-24 10:09:48.561 23440 23440 F DEBUG   :     #23 pc 00000000000237cc  /system/lib64/libc.so (__start_thread+68)

**Comment by GuaiYiHu** [comment]
08-24 13:29:23.904 22547 22547 E LoadedApk: Unable to instantiate appComponentFactory
08-24 13:29:23.904 22547 22547 E LoadedApk: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.app.CoreComponentFactory" on path: DexPathList[[zip file "/system/framework/android.test.mock.jar", zip file "/system/framework/android.test.runner.jar", zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.xunlei.downloadprovider-KN3vbWcbNhvzhh9XlycgnQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.xunlei.downloadprovider-KN3vbWcbNhvzhh9XlycgnQ==/lib/arm, /data/app/com.xunlei.downloadprovider-KN3vbWcbNhvzhh9XlycgnQ==/base.apk!/lib/armeabi-v7a, /system/lib]]
08-24 13:29:23.904 22547 22547 E LoadedApk: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
08-24 13:29:23.904 22547 22547 E LoadedApk: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
08-24 13:29:23.904 22547 22547 E LoadedApk: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
08-24 13:29:23.904 22547 22547 E LoadedApk: 	at android.app.LoadedApk.createAppFactory(LoadedApk.java:226)
08-24 13:29:23.904 22547 22547 E LoadedApk: 	at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:731)
08-24 13:29:23.904 22547 22547 E LoadedApk: 	at android.app.LoadedApk.getClassLoader(LoadedApk.java:810)
08-24 13:29:23.904 22547 22547 E LoadedApk: 	at android.app.LoadedApk.getResources(LoadedApk.java:1032)
08-24 13:29:23.904 22547 22547 E LoadedApk: 	at android.app.ContextImpl.createAppContext(ContextImpl.java:2345)
08-24 13:29:23.904 22547 22547 E LoadedApk: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5798)
08-24 13:29:23.904 22547 22547 E LoadedApk: 	at android.app.ActivityThread.access$1100(ActivityThread.java:200)
08-24 13:29:23.904 22547 22547 E LoadedApk: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
08-24 13:29:23.904 22547 22547 E LoadedApk: 	at android.os.Handler.dispatchMessage(Handler.java:106)
08-24 13:29:23.904 22547 22547 E LoadedApk: 	at android.os.Looper.loop(Looper.java:193)
08-24 13:29:23.904 22547 22547 E LoadedApk: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
08-24 13:29:23.904 22547 22547 E LoadedApk: 	at java.lang.reflect.Method.invoke(Native Method)
08-24 13:29:23.904 22547 22547 E LoadedApk: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
08-24 13:29:23.904 22547 22547 E LoadedApk: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
